### ISSUE TITLE
Layout usage

### ISSUE THREAD

**Issue by krucios** [bsu-mmf-2k4g2019/lab-1-DlLemmA#1]
Элементы управления не масштабируются при изменении размеров окна программы:
![изображение](https://user-images.githubusercontent.com/7770409/54549729-b2dc3a00-49bb-11e9-9455-e61646014503.png)
Пожалуйста, запретите изменение размера окна приложения или используйте Layout.

**Comment by DlLemmA** [comment]
На фото не моя программа

пн, 18 мар. 2019 г., 20:24 Andrei Pazniak <notifications@github.com>:

**Comment by krucios** [comment]
Да, действительно.
Прошу прощения, немного перепутал :)
